### ISSUE TITLE
BigQuery is very flakey on local / self-hosted

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/bigquery-plugin#10]
Bigquery client takes > 30s for insert requests when run locally. Need to investigate why this is happening, since if we're facing this, other self-hosted clients would be too.

What's mystifying is that it works perfectly fine on cloud - there's never* a timeout.

While we don't lose data, thanks to the retry job queues, it would be nice to figure out why this is happening in the first place.

---
More context: See https://github.com/PostHog/bigquery-plugin/pull/9

**Comment by Twixes** [comment]
Could you flesh this issue out a bit more please? I have no idea what the problem is without reading all of the linked issue (which is real ｌｏｎｇ)

**Comment by neilkakkar** [comment]
Local / self-hosted: 
![image](https://user-images.githubusercontent.com/7115141/122040749-1ab6a080-cdd0-11eb-8f64-b8136c986aee.png)

vs Cloud:

![image](https://user-images.githubusercontent.com/7115141/122040789-286c2600-cdd0-11eb-8ece-d98aa338aee0.png)

---

Note the timing differences, too!

**Comment by andrewm4894** [comment]
just adding an example from our posthog - lots of variance and some longish looking insert times and some failing it seems once they hit 30s

![image](https://user-images.githubusercontent.com/2178292/122430147-3ca85280-cf8b-11eb-9bf2-a457ba64b349.png)

**Comment by neilkakkar** [comment]
More data points: I tried the bigquery plugin while setting the `TASK_TIMEOUT` to 60 seconds, and I _still_ found similar issues (although a bit fewer, since it meant the requests taking between 30 to 60s were ok now).

Also, it probably doesn't have much to do with payload size. (i.e. have noticed smaller payloads taking a lot longer, and then succeeding almost instantly on retry)

Potential places to look for solutions:

- Tweaking the default cycle, maybe we're calling the `insertAll` endpoint too frequently?
- Existing client library issues / server issues.
- This doesn't inspire confidence: https://www.codementor.io/tips/0817274533/google-bigquery-slow-streaming-inserts-performance
