### ISSUE TITLE
What permissions are required?

### ISSUE THREAD

**Issue by edhgoose** [PostHog/bigquery-plugin#13]
I'd love to extend the README to include examples of what permissions a service account should have. I hope to develop this myself, but if anyone can help to describe them we'd appreciate it.

We'd love to know:
a) Which specific permissions are required
b) How to constrain them so that the Service Account only has access to the posthog dataset (and not other datasets in the same account).

**Comment by yakkomajuri** [comment]
Hey @edhgoose! I believe this should be a matter of granting all permissions to operate on that one table only, meaning setting the role `bigquery.dataOwner` scoped to the PostHog table should be it?

https://cloud.google.com/bigquery/docs/dataset-access-controls

**Comment by edhgoose** [comment]
Thanks @yakkomajuri - that helped, I was fiddling around in IAM permissions instead of in BigQuery dataset permissions. I've added an improved readme which should help for others in the future.
