### ISSUE TITLE
I would love to anonymise IP address (or exclude it)

### ISSUE THREAD

**Issue by edhgoose** [PostHog/bigquery-plugin#14]
We'd prefer if we weren't storing PII in our BigQuery dataset. I think most of it is excluded by virtue of only using `user_id` and other properties, but I note that the IP address is included in the events.

It'd be awesome to have a feature where the IP address is either anonymised (as a hash perhaps?) or removed.

I think a hash would be backwards compatible (for storing), as the schema is just a string?

**Comment by edhgoose** [comment]
I've subsequently realised there's an option to discard client ip data in Posthog itself, so I've actually just turned this on instead - so this is no longer important for me. Feel free to discard if you desire :)

**Comment by Twixes** [comment]
That's our suggested way indeed. :) I'll close this in this case.
