### ISSUE TITLE
Route events to different BigQuery tables 

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/bigquery-plugin#16]
Feature request from a customer:

> Right now all the events just go to one table. But that can become a bit of a bottle neck - it would be cool to be able to define a filter of some sort and define multiple output tables in BQ then.
>
> We are starting to have many different types of events and they all landing on one biggish table in BQ and is becoming a little messy on the ETL side - would be great if i could just define that some events go to table A in BQ and some go to table B etc.

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [BigQuery destination for batch exports](https://posthog.com/docs/cdp/batch-exports/bigquery).
