### ISSUE TITLE
Expected Behaviour for Existing Tables without defined schema

### ISSUE THREAD

**Issue by fxmb** [PostHog/bigquery-plugin#21]
**Problem**
=> We added BQ to our posthog and tried to load it into an `existing` table called `user_events`.
=> First, I did not add any schema at all as it isnt required by the docs. It throws an error then however and the plugin fails:
`setupPlugin failed with Error: Can not get metadata for table. Please check if the table schema is defined`

However, looking at the [code](https://github.com/PostHog/bigquery-plugin/blob/main/index.ts#L64) I do not think this is expected behaviour:

 ```
 if (!metadata.schema || !metadata.schema.fields) {
            throw new Error('Can not get metadata for table. Please check if the table schema is defined.')
        }
```

**Assumption**
Why wouldnt it just proceed to the matching fields step, here, opposed to throwing an error? I would expect the plugin to treat this just like a schema difference in general (since there is no schema so its different to the desired posthog schema), hence, it would create all required columns instead. Is there an apparent reason the plugin raises in that case? 

Right now, I have to either add a dummy schema beforehand or let the script **create** the table. Having the script handle a table without a schema does not seem to work. Am I missing something?

Thanks for your explanation 🙏

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [BigQuery destination for batch exports](https://posthog.com/docs/cdp/batch-exports/bigquery).
