### ISSUE TITLE
Missing user properties in exported events

### ISSUE THREAD

**Issue by nabeelz7** [PostHog/bigquery-plugin#29]
We're testing out this BigQuery Export app to export data to it but noticed any **custom user properties** (https://posthog.com/docs/getting-started/user-properties) are missing from the data export to BigQuery. This is important information for us to be able to export as it allows us to better map our data for our internal users.

The default `$set`, and `set_once` keys and values are present but not any custom user properties; example of such custom user properties as seen in "Events" of PostHog page:
![Screenshot 2023-06-30 at 11 52 58 AM](https://github.com/PostHog/bigquery-plugin/assets/73496207/7b4ad4d4-d2be-4faa-9ad7-1e8c880ba4b2)

Could it be an issue in this [code area](https://github.com/PostHog/bigquery-plugin/blob/main/index.ts#L207-L218) where we're it might be missing to pull in some other "event" property? Or something else going on?

Thanks!

**Comment by tiina303** [comment]
The BigQuery export app doesn't support exporting Person properties.

**Comment by nabeelz7** [comment]
@tiina303 thanks for the reply. Is that something in the plugin's roadmap? i.e. should I keep this issue open or "Close as not planned"?

**Comment by tiina303** [comment]
We're moving to a new export system see https://github.com/PostHog/posthog/issues/15997 . That said you might be interested in the data warehouse product we're working on https://posthog.com/docs/data-warehouse
